{
 "title": "go-ws",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container_name!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Master",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum by (cpu) (irate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\", instance=\"10.0.1.173:9100\"}[2m]))) * 100\n"
    },
    {},
    {}
   ]
  },
  {
   "title": "CPU - w1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum by (cpu) (irate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\", instance=\"10.0.2.17:9100\"}[2m]))) * 100\n"
    },
    {},
    {},
    {}
   ]
  },
  {
   "title": "CPU - w2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum by (cpu) (irate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\", instance=\"10.0.3.121:9100\"}[2m]))) * 100\n"
    },
    {}
   ]
  },
  {
   "title": "Master - mem usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.0.1.173:9100\"}\n    - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"10.0.1.173:9100\"}\n    - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"10.0.1.173:9100\"}\n    - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"10.0.1.173:9100\"}\n    )\n    / node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.0.1.173:9100\"}\n  ) * 100)\n"
    }
   ]
  },
  {
   "title": "W1 - mem usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.17:9100\"}\n    - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"10.0.2.17:9100\"}\n    - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"10.0.2.17:9100\"}\n    - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"10.0.2.17:9100\"}\n    )\n    / node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.17:9100\"}\n  ) * 100)\n"
    }
   ]
  },
  {
   "title": "W2 - mem usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.0.3.121:9100\"}\n    - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"10.0.3.121:9100\"}\n    - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"10.0.3.121:9100\"}\n    - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"10.0.3.121:9100\"}\n    )\n    / node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.0.3.121:9100\"}\n  ) * 100)\n"
    }
   ]
  },
  {
   "title": "Requests by Namespace",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container_name!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{container_name!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{container_name!=\"\"}) by (namespace) / sum(kube_pod_container_resource_limits_memory_bytes) by (namespace)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}